#!/bin/bash
#
. /usr/local/sbin/networking_defs.sh

PATH=/sbin:/usr/local/bin:$PATH

mkdir -p $ROUTE_INFO_PATH

case $reason in
    BOUND|RENEW|REBIND|REBOOT|TIMEOUT)
	# Store new router information
	echo "$new_routers" > $ROUTE_INFO_PATH/$interface.dat
	sync
	
	# IF_GW handled normally, no need to remove routes
	if [ "$interface" = "$IF_SHELL" ]; then
	    unset new_routers
	fi
	if [ "$interface" = "$IF_ASUKA" ]; then
	    unset new_routers
	fi
	if [ "$interface" = "$IF_LAN" ]; then
	    # LAN IF, shouldn't happen
	    unset new_routers
	fi
	;;
esac


