#!/bin/bash
#
. /usr/local/sbin/networking_defs.sh

PATH=/sbin:/usr/local/bin:$PATH

mkdir -p $ROUTE_INFO_PATH

case $reason in
    BOUND|RENEW|REBIND|REBOOT|TIMEOUT)
	# Store new router information
	echo "$new_routers" > $ROUTE_INFO_PATH/$interface.dat
	sync
	
	# GW (IF_PUB0) handled normally, no need to remove routes.
	# Other routes need to be operated.
	if [ "$interface" = "$IF_PUB1" ]; then
	    unset new_routers
	fi
	if [ "$interface" = "$IF_PUB2" ]; then
	    unset new_routers
	fi
	;;
esac


