#!/bin/bash
#
PATH=/sbin:/usr/local/bin:$PATH


case $reason in
    BOUND|RENEW|REBIND|REBOOT|TIMEOUT)

        # Usucal case: First ones are BOUND, rest RENEW

        if [ "$interface" = "eth0" ]; then
            /usr/local/sbin/update_dy_fi_address.sh $interface gw.asuka.dy.fi
        fi
        if [ "$interface" = "eth1" ]; then
            /usr/local/sbin/update_dy_fi_address.sh $interface shell.asuka.dy.fi
        fi
        if [ "$interface" = "eth2" ]; then
            /usr/local/sbin/update_dy_fi_address.sh $interface asuka.dy.fi
        fi
        ;;
esac
