#!/bin/sh

set -eu

pow () {
    local x y res i
    x=$1
    y=$2
    res=1
    i=1
    while [ $i -le $y ]; do
        res=$(( res * x ))
        i=$(( i + 1 ))
    done
    echo $res
}

# Helper funcion to dotted_decimal_to_numeric
spaced_decimal_to_numeric () {
        local addr=$((16777216 * $1 + 65536 * $2 + 256 * $3 + $4))
        echo $addr
}

numeric_to_dotted_decimal () {
        local group1=$(($1 / 16777216))
        local remainder1=$(($1 - ($group1 * 16777216)))
        local group2=$(($remainder1 / 65536))
        local remainder2=$(($remainder1 - ($group2 * 65536)))
        local group3=$(($remainder2 / 256))
        local group4=$(($remainder2 - ($group3 * 256)))
        echo "$group1.$group2.$group3.$group4"
}

pingscan_worker () {
        local up_address=$(ping -W 1 -c 1 $(numeric_to_dotted_decimal $1) | grep "bytes from" | awk '{print $4}' | tr -d ':')
        if [ "$up_address" = "" ]; then
                return 1
        fi
        echo $up_address
        return 0
}

pingscan () {
        local spaced_addr="$(echo $1 | cut -d'/' -f1 | cut -d. -f1-4 | tr . ' ')"
        local numeric_addr=$(spaced_decimal_to_numeric $spaced_addr)
        local mask=$(echo $1 | cut -d'/' -f2)
        local net_bits=$((32 - $mask))
        local numeric_mask=$(pow 2 $net_bits)
        local network_addr=$(($numeric_addr / $numeric_mask * $numeric_mask))
        local first_addr=$(($network_addr + 1))
        local last_addr=$(($network_addr + $numeric_mask - 2))
        local first_addr_text=$(numeric_to_dotted_decimal $first_addr)
        local last_addr_text=$(numeric_to_dotted_decimal $last_addr)
        >&2 echo "Scanning range ${first_addr_text} - ${last_addr_text}"
        local up=0
        for ip_addr in $(seq $first_addr $last_addr); do
                 pingscan_worker $ip_addr && up=$(($up + 1)) &
        done | grep ""
}

# Require interface name
if [ -z ${1+0} ]; then
        echo "usage: $0 interface_name"
        exit 0
fi

# The space in grep is important. We only want IPv4.
addr=$(ip addr show dev $1 | grep -m 1 "inet " | awk '{print $2}')
if [ "$addr" = "" ]; then
        >&2 echo "Error: iface $1 has no usable addresses"
        exit 1
fi

pingscan $addr
